version: '3.8'
services:
  web:
    build: 
        context: ./
        dockerfile: ./docker/web/Dockerfile
    # volumes:
    #   - ./frontend:/src
    command: node index.js
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
